# Generated by Django 4.1.7 on 2023-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('inviteCode', models.CharField(db_column='invite_code', max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'invite_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserIndex',
            fields=[
                ('userIndex', models.CharField(db_column='user_reference', max_length=16, primary_key=True, serialize=False)),
                ('userAccount', models.CharField(db_column='user_account', max_length=10, unique=True)),
                ('userPassword', models.CharField(db_column='user_password', max_length=15)),
                ('userUUID', models.CharField(db_column='user_uuid', max_length=32, unique=True)),
            ],
            options={
                'db_table': 'user_index',
                'managed': False,
            },
        ),
    ]
